linz/emergency-management-tools

- flooding/Sentinel2_Water_Extraction/Sentinel2_Water_Extraction.ipynb
- flooding/Sentinel2_Water_Extraction/out/.gitignore
But separate from source, to make sure it doesn't clutter the filesystem.
> fix: Send output to existing directory

- flooding/Sentinel2_Water_Extraction/bump-nixpkgs.bash
- flooding/Sentinel2_Water_Extraction/nixpkgs.json
- flooding/Sentinel2_Water_Extraction/shell.nix
Also introduce an easy way to bump it by simply running `./bump-nixpkgs.bash` to check for a new nixpkgs version, and update `nixpkgs.json` if so.
> build: Bump nixpkgs

- flooding/Sentinel2_Water_Extraction/bump-nixpkgs.bash
By convention the old file should be on the left and the new file is on
the right of the diff.
> refactor: Swap old and new files for clearer diff

- .github/workflows/test.yml
Avoids random breakage when GitHub updates their runners.
> build: Use specific Ubuntu version

- .github/workflows/test.yml
It looks like all the Linux, macOS, and Windows runners already have up-to-date pip installed, so this step is probably redundant.
> chore: Remove pip upgrade

- .github/workflows/test.yml
- flooding/sentinel2_water_extraction/README.md
Challenges:
- [GDAL 3.4.1 is not available for installation with brew](https://formulae.brew.sh/formula/gdal)
- [Poetry ignores declaration of different versions for macOS and Linux](https://github.com/python-poetry/poetry/issues/5506)
- [Conda does not yet support Python 3.11](https://github.com/conda/conda/issues/11170)
> test: Poetry on MacOS

- .github/workflows/test.yml
- flooding/sentinel2_water_extraction/README.md
Challenges:
- [Python directory tree removal is flaky on Windows](https://github.com/python/cpython/issues/59701), and therefore [also in Poetry](https://github.com/python-poetry/poetry-core/pull/460).
- [Geopandas flakiness when used with Shapely<2 on Windows](https://github.com/geopandas/geopandas/issues/2766).
- [Flaky Conda/Python 3.10/Windows combination](https://github.com/nltk/nltk/issues/3027#issuecomment-1197689886).
> test: Poetry on Windows

- .github/workflows/test.yml
This will hopefully avoid some issues with installing Poetry a second time using Conda, at the cost of more risk since we're not using a proper parser for the `poetry.lock` file.
> fix: Avoid installing multiple Poetry versions

- .github/workflows/test.yml
Simplifies the structure, and avoids accidentally running in the wrong Nix shell.
> build: Apply working directory to entire jobs

- .github/workflows/jekyll-gh-pages.yml
Otherwise PRs clobber each others' build jobs.
> fix: Cancel only deploy jobs on master

- .github/workflows/test.yml
macOS 12 `head` does not support negative indexes, resulting in an empty string, which unfortunately does not cause `conda install` to fail. This way should be compatible with even very old POSIX-y shells.
Another advantage of this approach is not running any extra tools.
> fix: macOS GDAL version fetching

- .github/workflows/test.yml
Poetry 1.4.0 is broken on Windows
<https://github.com/python-poetry/poetry/issues/7589>.
> fix: Downgrade Poetry below 1.4

- .envrc
- flooding/sentinel1_water_extraction/.envrc
- flooding/sentinel2_water_extraction/.envrc
- machine-readable-to-human-readable-date-time/.envrc
`shell.nix` files are watched automatically, but everything else that's an input to the shell needs to be watched explicitly to avoid having to run `direnv reload` manually.
> feat: Watch more files relevant to Nix shells

- .envrc
- .gitignore
- _config.yml
- shell.nix
direnv does not run the `shellHook`, so we need a separate mechanism to
make sure the Python interpreter is available for example to IDEs.
> feat: Implement stable path to Python interpreter in direnv 

- shell.nix
Necessary for JetBrains IDEA to detect Python packages: <https://youtrack.jetbrains.com/issue/PY-58418/Python-packaging-tools-not-found# focus=Comments-27-7857731.0-0>.
> feat: Install setuptools

- .github/workflows/test.yml
About 1/3rd of Conda installs are broken, so this should halve the risk of a broken pipeline without increasing the risk of version incompatibility too much.
> test: Run only against oldest and latest supported Python

- .github/workflows/jekyll-gh-pages.yml
- .github/workflows/test.yml
Done with pin-github-action <https://github.com/mheap/pin-github-action> 1.8.0 using `npx pin-github-action --comment=' {ref}' .github/workflows/*.y*ml`.
Dependabot should support updating in the same fashion <https://github.com/dependabot/dependabot-core/issues/8277#issuecomment-1782819752>.
Had to `export GH_ADMIN_TOKEN=github_pat_…` using a fine-grained personal access tokens with no extra access to work around rate limiting *and* to be able to work in private repos
<https://github.com/mheap/pin-github-action/issues/73>.
> feat: Pin actions to hashes TDE-934

- .github/workflows/test.yml
Upgrades to 1.8 are [blocked by a Conda issue](https://github.com/conda-forge/poetry-feedstock/issues/101).
~~Blocked by <https://github.com/pypa/pip/pull/11394>, which should be part of the next pip release, >23.2.1.~~
> build: Use Poetry 1.7.1

- .github/workflows/jekyll-gh-pages.yml
- .github/workflows/test.yml
Still test Conda/Poetry use on Ubuntu 22.04, since that will be the most common platform for some time.
> build: Run jobs on Ubuntu 24.04

- .github/workflows/test.yml
build: Install Poetry with pipx
As [recommended by the documentation](https://python-poetry.org/docs/#ci-recommendations) and
[@xylar](https://github.com/conda-forge/poetry-feedstock/issues/101#issuecomment-2113996440).
This should avoid the "No such file or directory:
'/usr/local/miniconda/envs/test/lib/python3.[…]/site-packages/[…].dist-info'"
errors which probably comes from the interaction between Conda and Poetry.
> build: Install Poetry with pipx
